Repository cse110-fq22-group40/cse110-fq22-group40, pull requests merged in 2022-12, with the labels that each got.

#171 72 empty bug
  source/client/assets/scripts/type-f/type-f.js
  source/local/imports.js
  source/local/scripts/folders.js
  source/local/scripts/notes.js
  source/local/scripts/utils.js
Labels: bug

#181 Styling Assignment - Ernest
  source/client/assets/scripts/type-a/audio-object-create-screen.js
  source/local/scripts/utils.js
Labels: documentation

#226 205 update unit tests
  source/local/scripts/utils.js
  testing/audio-object.test.js
  testing/audio.test.js
  testing/folders.test.js
  testing/notes.test.js
  testing/type-a.test.js
  testing/type-f.test.js
  testing/utils.test.js
Labels: qa-testing

#224 add e2e adr, explain why we didnt test audio files
  specs/adrs/112922_E2E-Framework.md
Labels: documentation
